import type { ReactNode } from 'react';

const REPO = 'https://github.com/minchiaHuang/minchiahuang.dev';

const STEPS = [
  'Spec + plan (human + Claude)',
  'blender/scene_v2.py builds the room, desk and CRT',
  'Cycles bakes light into 3 lightmaps, then OpenImageDenoise',
  'glTF export → glTF-Transform (meshopt, WebP)',
  'Vite builds the three.js scene + the React OS',
  'bin/verify.sh: credits & name check, 5 MB budget, phone check',
  'Cloudflare Pages',
];

const BOX_W = 560;
const BOX_H = 44;
const GAP = 26;

// The pipeline as boxes joined by arrows. currentColor and inherited fonts keep it in step with the window text.
function Flow() {
  const h = STEPS.length * BOX_H + (STEPS.length - 1) * GAP + 4;
  return (
    <svg className="as-flow" viewBox={`0 0 ${BOX_W + 4} ${h}`} role="img" aria-label="Build pipeline, top to bottom">
      <defs>
        <marker id="as-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="8" markerHeight="8" orient="auto">
          <path d="M0 0L10 5L0 10z" fill="currentColor" />
        </marker>
      </defs>
      {STEPS.map((label, i) => {
        const y = 2 + i * (BOX_H + GAP);
        return (
          <g key={label}>
            <rect x="2" y={y} width={BOX_W} height={BOX_H} fill="none" stroke="currentColor" strokeWidth="2" />
            <text x={BOX_W / 2 + 2} y={y + BOX_H / 2} textAnchor="middle" dominantBaseline="central" fill="currentColor" fontSize="15">
              {label}
            </text>
            {i < STEPS.length - 1 && (
              <line
                x1={BOX_W / 2 + 2}
                y1={y + BOX_H}
                x2={BOX_W / 2 + 2}
                y2={y + BOX_H + GAP - 2}
                stroke="currentColor"
                strokeWidth="2"
                markerEnd="url(#as-arrow)"
              />
            )}
          </g>
        );
      })}
    </svg>
  );
}

const Ext = ({ href, children }: { href: string; children: ReactNode }) => (
  <a href={href} target="_blank" rel="noreferrer">
    {children}
  </a>
);

export default function AboutSite() {
  return (
    <div className="as">
      <h1>How this site was built</h1>
      <p>
        This whole scene is generated by code. Claude wrote a Blender script; I reviewed the preview images and steered. Nothing
        here was modelled by hand.
      </p>
      <Flow />
      <h2>How the work was split</h2>
      <p>
        The work ran through an agent-flow: one manager session cut the plan into packages and started a worker for each. Every
        worker built its package in its own git worktree and opened one pull request. A single merge queue then merged the pull
        requests, ran the full check and deployed.
      </p>
      <h2>Source</h2>
      <ul>
        <li>
          <Ext href={REPO}>Repository</Ext>
        </li>
        <li>
          <Ext href={`${REPO}/blob/main/blender/scene_v2.py`}>blender/scene_v2.py</Ext>, the scene script
        </li>
        <li>
          <Ext href={`${REPO}/blob/main/CREDITS.md`}>CREDITS.md</Ext>, every third-party file and its licence
        </li>
      </ul>
    </div>
  );
}
