import { useEffect, useState } from 'react';

interface Section {
  title: string;
  rows: [string, string][];
  note?: string;
}

// Each click shows the next page; the last click starts over from the first. A page also moves on by itself
// after a few seconds (the original went to its next section about 5.5s after the first one appeared).
const AUTO_MS = 5500;
const PAGES: Section[][] = [
  [
    {
      title: '3D Scene',
      rows: [
        ['Min-Chia (Tommy) Huang', 'Art direction'],
        ['Claude (Anthropic)', 'Blender scene script'],
        ['Kenney', 'Books model (CC0)'],
      ],
      note: 'The desk, CRT and room are generated by blender/scene_v2.py and baked into lightmaps.',
    },
  ],
  [
    {
      title: 'Engineering & Design',
      rows: [
        ['Min-Chia (Tommy) Huang', 'Software Engineer'],
        ['Min-Chia (Tommy) Huang', 'Operating system, Five Letters, Credits'],
        ['Min-Chia (Tommy) Huang', 'My Showcase content'],
      ],
    },
  ],
  [
    {
      title: 'Fonts',
      rows: [
        ['Nunito Sans', 'The Nunito Sans Project Authors'],
        ['VT323', 'Peter Hull, The VT323 Project Authors'],
      ],
      note: 'Both fonts are licensed under the SIL Open Font License 1.1.',
    },
  ],
  [
    {
      title: 'Sound & Assets',
      rows: [
        ['Kenney', 'Furniture model and UI sounds (CC0)'],
        ['Monitor glass & noise', 'Generated in code'],
        ['Mac OS X 10.0 icons', '© Apple Inc.'],
        ['Game logos', '© their publishers'],
      ],
    },
  ],
  [
    {
      title: 'Games',
      rows: [
        ['Doom (shareware)', 'id Software, via js-dos archive'],
        ['The Oregon Trail Deluxe', 'MECC, via js-dos archive'],
        ['Scrabble', 'U.S. Gold, via archive.org'],
        ['js-dos & DOSBox', 'Emulator'],
      ],
    },
  ],
];

export default function Credits() {
  // -1: nothing shown but the prompt; the first click shows page 0, later clicks advance (the last wraps to the first).
  const [page, setPage] = useState(-1);
  const [tick, setTick] = useState(0);

  // The row of dots under the prompt counts up and starts over.
  useEffect(() => {
    const id = setInterval(() => setTick((t) => t + 1), 450);
    return () => clearInterval(id);
  }, []);

  // Restarted on every page change, so a click gives the new page its full time.
  useEffect(() => {
    if (page < 0) return;
    const id = setTimeout(() => setPage((p) => (p + 1) % PAGES.length), AUTO_MS);
    return () => clearTimeout(id);
  }, [page]);

  return (
    <div className="cr" onClick={() => setPage((p) => (p + 1) % PAGES.length)}>
      {page >= 0 && (
        <>
          <div className="cr-head">
            <h1>Credits</h1>
            <div className="cr-sub">A practice rebuild, 2026</div>
          </div>
          <div key={page} className="cr-page is-fade">
            {PAGES[page].map((s) => (
              <section key={s.title} className="cr-section">
                <h2>{s.title}</h2>
                {s.rows.map(([name, role], i) => (
                  <div key={i} className="cr-row">
                    <span>{name}</span>
                    <span>{role}</span>
                  </div>
                ))}
                {s.note && <p>{s.note}</p>}
              </section>
            ))}
          </div>
        </>
      )}
      <div className="cr-foot">
        <div className="cr-prompt">Click to continue…</div>
        <div className="cr-dots">{Array.from({ length: (tick % 4) + 1 }, () => '.').join(' ')}</div>
      </div>
    </div>
  );
}
